### PR TITLE
elastic #60750

### PR DESCRIPTION
**Pull request by mun-inder-jeet-singh**
Added Composable Index Template Builder

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by mun-inder-jeet-singh** [comment]
Hi @dakrone , Kindly review this draft .

Motivation for this code is ofcourse @antrix190.

**Comment by antrix190** [comment]
@mun-inder-jeet-singh that's exactly my code. Tell me a reason why should this PR be merged and not mine?

**Comment by mun-inder-jeet-singh** [comment]
> @mun-inder-jeet-singh that's exactly my code and if you've signed the CLA(which you have), it's a voilation of the agreement.
> If you want to improve/suggest changes for my code, raise a PR rather than copying my code and submitting as your contribution. The issue had no asignee and hence i confirmed before starting. What you did is not appreciated at all.

@antrix190  I was already working on this issue. Obviously it has no assignee but i was working on it as you can get an idea from previous comments.

I believe you should confirmed with me before raising a PR. (Your PR was raised just after 2-3 hrs before asking to contribute and no one even confirms if you can or not).

Also as there was no response in issue i thought you left this issue, but the fact is i was working on it before you came and you did not confirmed if i was working on it or not. (This is because i also spent much time on it, and it just don't feel right when you get confirmed to resolve the issue and someone came and requested for PR right away).

Ofcourse it looks exactly same code, as @dakrone suggested this only. 
Still my first tryout ruined :-(

**Comment by antrix190** [comment]
So the thing is i confirmed with @dakrone on this and he confirmed that it's not completed yet.(In which you were copied as well)
Sure you worked on it but 1. you copied my code exactly with your commit., 2. you didn't reply in time or confirm in even when you were copied.
Raising a PR in 2-3 hours can never be an issue.

You JUST CAN'T copy code. Period. That's not how opensource works.
And for future tickets, get it assigned so that nobody else spends time on it because Opensource community has millions of developers who are eager to contribute.

Also if you come and comment after the PR is raised (which is after 2-3 hours as you said) do you think i should take back my contribution in an open source project. This is unprofessional and against the CLA. 

There are no "Taking motivation" without the consent of the developer. 
I don't think it is negotiable here. @dakrone need your intervention here.

**Comment by mun-inder-jeet-singh** [comment]
> So the thing is i confirmed with @dakrone on this and he confirmed that it's not completed yet.(In which you were copied as well)
> Sure you worked on it but 1. you copied my code exactly with your commit., 2. you didn't reply in time or confirm in even when you were copied.
> Raising a PR in 2-3 hours can never be an issue.
> 
> You JUST CAN'T copy code. Period. That's not how opensource works.
> And for future tickets, get it assigned so that nobody else spends time on it because Opensource community has millions of developers who are eager to contribute.
> 
> Also if you come and comment after the PR is raised (which is after 2-3 hours as you said) do you think i should take back my contribution in an open source project. This is unprofessional and against the CLA.
> 
> There are no "Taking motivation" without the consent of the developer.
> I don't think it is negotiable here. @dakrone need your intervention here.

Let @dakrone decide and if it is wrong I will remove this commit and suggest another solution.

**Comment by antrix190** [comment]
Sure thing. I will waiting your reply @dakrone.

**Pull request closed without merging**
